import React, { Component } from 'react';
import * as d3 from "d3";

class Histogram extends Component {
  // constructor(props){
  //   super(props);
  //
  //   //this.createHistogram = this.createHistogram.bind(this)
  // }
  componentDidMount() {
    console.log(this.props);
    this.createHistogram();
  }
  componentDidUpdate() {
    this.createHistogram();
  }
  createHistogram() {

    console.log("rendering ;)", this.props.totalMembers, this.props.partyMembers)
    // node in svg element acts as a reference to the actual DOM node generated by React
    const node = this.node;

    // margins and dimensions
    const margin = {top:20, right:20, bottom: 100, left: 100};
    const graphWidth = 500 - margin.left - margin.right;
    const graphHeight = 400 - margin.top - margin.bottom;

    //create a group for bars, add width/height attributes
    const graph = d3.select(node).append('g')
      .attr('width', graphWidth)
      .attr('height', graphHeight)
      .attr('transform', `translate(${margin.left}, ${margin.top})`)


  }
  render() {

    return <svg
      ref={node => this.node = node}
      width='500'
      height='400'>
      </svg>
  }
}

export default Histogram;
